In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk 
import os
import webbrowser
import plotly.express as px
import plotly.io as pio
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from datetime import datetime
import pytz

In [2]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [3]:
apps_df=pd.read_csv("Play Store Data.csv")
reviews_df=pd.read_csv("User Reviews.csv")

In [4]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [5]:
reviews_df

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
...,...,...,...,...,...
64290,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64294,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

In [6]:
apps_df['Installs']=apps_df['Installs'].str.replace(',','').str.replace('+','')

In [7]:
apps_df['Price']=apps_df['Price'].str.replace('$','')

In [8]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,1000,Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [9]:
merged_df=pd.merge(apps_df,reviews_df, on='App', how='inner')

In [10]:
merged_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN,NaN,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122657,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122658,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122659,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122660,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122661,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN

In [11]:
apps_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Length: 10841, dtype: bool

In [12]:
reviews_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
64290     True
64291     True
64292     True
64293     True
64294     True
Length: 64295, dtype: bool

In [13]:
apps_df=apps_df.dropna(subset=['Rating'])
for column in apps_df.columns:
    apps_df[column].fillna(apps_df[column].mode()[0],inplace=True)
apps_df.drop_duplicates(inplace=True)
apps_df=apps_df=apps_df[apps_df['Rating']<=5]
reviews_df.dropna(subset=['Translated_Review'],inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_16556\1024063703.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  apps_df[column].fillna(apps_df[column].mode()[0],inplace=True)

In [14]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [15]:
def convert_size(size):
    if 'M' in size:
        return float(size.replace('M',''))
    elif 'K' in size:
        return float(size.replace('K',''))/1024
    else:
        return np.nan
apps_df['Size']=apps_df['Size'].apply(convert_size)

In [16]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [17]:
apps_df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,False,False,False,False,False,False,False,False,False,False,False,False,False
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,True,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
apps_df.describe()

            Rating         Size
count  8892.000000  7167.000000
mean      4.187877    23.547956
std       0.522377    23.460103
min       1.000000     1.000000
25%       4.000000     5.700000
50%       4.300000    15.000000
75%       4.500000    34.000000
max       5.000000   100.000000

In [19]:
apps_df.info()

<class 'pandas.DataFrame'>
Index: 8892 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8892 non-null   str
 1   Category        8892 non-null   str
 2   Rating          8892 non-null   float64
 3   Reviews         8892 non-null   str
 4   Size            7167 non-null   float64
 5   Installs        8892 non-null   str
 6   Type            8892 non-null   str
 7   Price           8892 non-null   str
 8   Content Rating  8892 non-null   str
 9   Genres          8892 non-null   str
 10  Last Updated    8892 non-null   str
 11  Current Ver     8888 non-null   str
 12  Android Ver     8890 non-null   str
dtypes: float64(2), str(11)
memory usage: 972.6 KB

In [20]:
apps_df['Last Updated']=pd.to_datetime(apps_df['Last Updated'], errors='coerce')

In [21]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device

In [22]:
apps_df['Month']=apps_df['Last Updated'].dt.month

In [23]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [24]:
avg_rating = apps_df.groupby('Category')['Rating'].mean()

In [25]:
sorted_df=apps_df.groupby('Category').agg({
    'Rating': 'mean', 
    'Reviews': 'sum',
    'Installs':'sum'
})

In [26]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [27]:
sorted_df

,Rating,Reviews,Installs
Category,,,
ART_AND_DESIGN,4.358065,1599678751021564496716717836815137911211388087...,1000050000050000005000000010000050000500001000...
AUTO_AND_VEHICLES,4.190411,3671598284170571295421047980512914033971534777...,1000001000000100000100000010000010000010000050...
BEAUTY,4.278571,1890049790115017393209022254369857296442050104...,5000001000000100000500000100000050000010000010...
BOOKS_AND_REFERENCE,4.347458,2914724185744785775508140802463154540601554464...,1000000005000010000010000000100000000100000001...
BUSINESS,4.102593,1612967473012547308518532584217730709911002861...,1000000050000000100000005000000100000050000000...
COMICS,4.155172,1013635240055710622495168341010238970302438733...,1000000050000010000005000005000050000500001000...
COMMUNICATION,4.151466,5664284769119316125257964299514290354604324341...,1000000000100000000010000000100000000010000000...
DATING,3.971698,1545572516801285726766462556777961637126323137...,1000010001001000000010000000100000001000005000...
EDUCATION,4.375969,6289924181893254485375314299977032346407510611...,1000000001000000010000050000001000000050000001...
ENTERTAINMENT,4.136036,5456208116562894829677147008910939985095241225...,1000000001000000100000010000000500000001000000...
EVENTS,4.435556,3782401137074215326089206118111555857382323089...,1000005000000500000500005000000100000010000100...
FAMILY,4.191153,4706944214544499101477412753339832026757611161...,5000000010000000100000000100000050000005000000...
FINANCE,4.127445,1244243904152306367184264427808260761126563357...,1000000010000005000000500000050000001000000050...
FOOD_AND_DRINK,4.164151,1453236478432997270712973761113661182473109784...,1000000010000000100000010000010000001000000010...
GAME,4.281285,4447388277222642242667725425814889736920352341...,1000000001000000000500000000100000001000000050...
HEALTH_AND_FITNESS,4.261450,4281561577380983113927233722012540059220098117...,1000000050000050000001000000100000001000000010...
HOUSE_AND_HOME,4.164706,4179073167273861622436591324977600037711175293...,1000000010000010000001000000050000001000000100...
LIBRARIES_AND_DEMO,4.178462,2087583014923670075391268624814659297832907434...,5000010000100000100000500000050000100000001000...
LIFESTYLE,4.096066,1896847497601140995513571356539364728716114316...,5000000100000001000001000000050000001000000500...
MAPS_AND_NAVIGATION,4.051613,7232629156815348110480050459432695644349284201...,1000000005000000100000001000000050000005000000...
MEDICAL,4.182450,1135578129632161714571729211533921991361121520...,1000001000010000100001000010000500050001000005...
NEWS_AND_MAGAZINES,4.128505,2499191581964262426411296781297063069383558606...,1000000010000000100000010000001000000010000001...
PARENTING,4.300000,8617941361414133937891075594976449293623861621...,1000050000001000000100000100001000000500001000...
PERSONALIZATION,4.333871,1121805714664666414965717241392583279410292367...,5000000010000001000000005000000100000500000050...
PHOTOGRAPHY,4.182895,1923298716109500211591320504243239810858556219...,1000000500000010000005000005000010000001000000...
PRODUCTIVITY,4.201796,2084126536926301629711881542731171822622879432...,5000000001000000010000000010000000100000000010...
SHOPPING,4.251485,1416136210998591312942946087533896159166064414...,1000000010000000010000000100000001000000050000...
SOCIAL,4.254918,7815830666577313860625949173295532622492170147...,1000000000100000000050000000010000000100000000...
SPORTS,4.225175,5211381802283662828824597951338259119951733342...,1000000010000010000000500000050000000100000001...
TOOLS,4.047411,3865580334935745093182392419937333127596633083...,1000000010000000005000000001000000050000000500...
TRAVEL_AND_LOCAL,4.094146,1366262198485202949190515064713216388481545601...,1000000050000000500000010000005000001000000100...
VIDEO_PLAYERS,4.063750,2565530575575908915511276454807259003121916400...,1000000000100000010000000100000010000001000000...
WEATHER,4.244000,1558437159455205340489298199511118178934112971...,5000000010000005000000010000100000001000000100...

In [28]:
apps_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                      str
Size                     float64
Installs                     str
Type                         str
Price                        str
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
dtype: object

In [29]:
apps_df['Reviews'] = apps_df['Reviews'].astype(int)
apps_df['Installs']=apps_df['Installs'].astype(int)

In [30]:
apps_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                        str
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
dtype: object

In [31]:
sorted_df=apps_df.groupby('Category').agg({
    'Rating': 'mean', 
    'Reviews': 'sum',
    'Installs':'sum'
})

In [32]:
sorted_df

                       Rating     Reviews     Installs
Category
ART_AND_DESIGN       4.358065     1714372    124233100
AUTO_AND_VEHICLES    4.190411     1163630     53129800
BEAUTY               4.278571      395133     26916200
BOOKS_AND_REFERENCE  4.347458    21872818   1916291655
BUSINESS             4.102593    12357705    863518120
COMICS               4.155172     3381945     56036100
COMMUNICATION        4.151466   601273091  24152241530
DATING               3.971698     5545164    206522410
EDUCATION            4.375969    23164724    533852000
ENTERTAINMENT        4.136036    47570716   2455660000
EVENTS               4.435556      160590     15949410
FAMILY               4.191153   396768720  10041130590
FINANCE              4.127445    16999569    770312400
FOOD_AND_DRINK       4.164151     7671255    257777750
GAME                 4.281285  1415533878  31543862717
HEALTH_AND_FITNESS   4.261450    30845065   1361006220
HOUSE_AND_HOME       4.164706     2794391    125082000
LIBRARIES_AND_DEMO   4.178462     1033535     62083000
LIFESTYLE            4.096066    12819560    534741120
MAPS_AND_NAVIGATION  4.051613    30659060    724267560
MEDICAL              4.182450     1396427     42162676
NEWS_AND_MAGAZINES   4.128505    38244909   5393110650
PARENTING            4.300000      953609     31116110
PERSONALIZATION      4.333871    75192838   2074352930
PHOTOGRAPHY          4.182895   204297367   9721243130
PRODUCTIVITY         4.201796   102554240  12463070180
SHOPPING             4.251485    94930973   2573331540
SOCIAL               4.254918   533576498  12513841475
SPORTS               4.225175    65322107   1528531465
TOOLS                4.047411   273184168  11450724500
TRAVEL_AND_LOCAL     4.094146    55565013   6361859300
VIDEO_PLAYERS        4.063750   110379692   6221897200
WEATHER              4.244000    14604695    426096500

In [33]:
filtered_df=apps_df[
    (apps_df['Rating'] >=4) & 
    (apps_df['Size'] >=10) & 
    (apps_df['Month'] ==1)
]

In [34]:
filtered_df.shape

(127, 14)

In [35]:
filtered_df['Rating'].min()

np.float64(4.0)

In [36]:
filtered_df['Size'].min()

np.float64(11.0)

In [37]:
filtered_df['Month'].unique()

array([1], dtype=int32)

In [38]:
summary_df = filtered_df.groupby('Category')

In [39]:
summary_df

In [40]:
summary_df = filtered_df.groupby('Category').agg({
    'Rating': 'mean',
    'Reviews': 'sum',
    'Installs': 'sum'
})

In [41]:
summary_df

                       Rating  Reviews   Installs
Category
ART_AND_DESIGN       4.166667     1200     120000
BOOKS_AND_REFERENCE  4.600000       33       1000
BUSINESS             4.900000       18       1200
COMMUNICATION        4.200000    15287    1000000
EDUCATION            4.400000    57645    2000000
ENTERTAINMENT        4.300000   869111   21000000
EVENTS               4.800000        8        500
FAMILY               4.395455  4544623  182494820
FINANCE              4.450000     1237      55000
FOOD_AND_DRINK       4.600000      556     100000
GAME                 4.313333  2397589  115691000
LIFESTYLE            4.380000    42809    5071000
MEDICAL              4.533333      420      62600
PARENTING            5.000000        1         10
PERSONALIZATION      4.475000   155996   15060000
PHOTOGRAPHY          4.150000   563720   10500000
PRODUCTIVITY         4.400000      685     510000
SHOPPING             4.200000     9975    1000000
SOCIAL               4.500000      431      17000
SPORTS               4.342857  1982017  120511000
TOOLS                4.200000     8010    1010000
TRAVEL_AND_LOCAL     4.100000      974    1001000

In [42]:
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist).time()

In [43]:
plot_containers=""

In [44]:
html_files_path="./"
if not os.path.exists(html_files_path):plot_width = 600

In [45]:
Task_1=summary_df.nlargest(10, 'Installs')

In [46]:
Task_1

                    Rating  Reviews   Installs
Category
FAMILY            4.395455  4544623  182494820
SPORTS            4.342857  1982017  120511000
GAME              4.313333  2397589  115691000
ENTERTAINMENT     4.300000   869111   21000000
PERSONALIZATION   4.475000   155996   15060000
PHOTOGRAPHY       4.150000   563720   10500000
LIFESTYLE         4.380000    42809    5071000
EDUCATION         4.400000    57645    2000000
TOOLS             4.200000     8010    1010000
TRAVEL_AND_LOCAL  4.100000      974    1001000

In [47]:
Task_1 = Task_1.reset_index()

In [48]:
Task_1

           Category    Rating  Reviews   Installs
0            FAMILY  4.395455  4544623  182494820
1            SPORTS  4.342857  1982017  120511000
2              GAME  4.313333  2397589  115691000
3     ENTERTAINMENT  4.300000   869111   21000000
4   PERSONALIZATION  4.475000   155996   15060000
5       PHOTOGRAPHY  4.150000   563720   10500000
6         LIFESTYLE  4.380000    42809    5071000
7         EDUCATION  4.400000    57645    2000000
8             TOOLS  4.200000     8010    1010000
9  TRAVEL_AND_LOCAL  4.100000      974    1001000

In [49]:
Task_1 = Task_1[['Category', 'Rating', 'Reviews']]

In [50]:
Task_1_melted = Task_1.melt(
    id_vars='Category',
    value_vars=['Rating', 'Reviews'],
    var_name='Metric',
    value_name='Value'
)

In [51]:
Task_1

           Category    Rating  Reviews
0            FAMILY  4.395455  4544623
1            SPORTS  4.342857  1982017
2              GAME  4.313333  2397589
3     ENTERTAINMENT  4.300000   869111
4   PERSONALIZATION  4.475000   155996
5       PHOTOGRAPHY  4.150000   563720
6         LIFESTYLE  4.380000    42809
7         EDUCATION  4.400000    57645
8             TOOLS  4.200000     8010
9  TRAVEL_AND_LOCAL  4.100000      974

In [52]:
fig1= px.bar(
    Task_1,
    x='Category',
    y=['Rating', 'Reviews'],
    barmode='group',
    title='Top 10 Categories: Rating vs Reviews',
    color_discrete_sequence=px.colors.qualitative.Safe,
    width=400,
    height=300
)
fig1.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    margin=dict(l=10, r=10, t=30, b=10)
)
start_time = datetime.strptime("15:00", "%H:%M").time()
end_time = datetime.strptime("17:00", "%H:%M").time()

if start_time <= current_time <= end_time:
    fig1.show()
else:
    print("Chart is available only between 3:00 PM and 5:00 PM IST.")

Chart is available only between 3:00 PM and 5:00 PM IST.

In [53]:
apps_df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Month'],
      dtype='str')

In [54]:
reviews_df.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='str')

In [55]:
task3_df=apps_df.copy()

In [56]:
task3_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [57]:
task3_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                        str
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
dtype: object

In [58]:
merged_df['Price']=merged_df['Price'].astype(float)
merged_df['Installs']=merged_df['Installs'].astype(int)

In [59]:
merged_df.dtypes

App                           str
Category                      str
Rating                    float64
Reviews                       str
Size                          str
Installs                    int64
Type                          str
Price                     float64
Content Rating                str
Genres                        str
Last Updated                  str
Current Ver                   str
Android Ver                   str
Translated_Review             str
Sentiment                     str
Sentiment_Polarity        float64
Sentiment_Subjectivity    float64
dtype: object

In [60]:
print(type(task3_df))

<class 'pandas.DataFrame'>

In [61]:
print(task3_df[['Price', 'Installs']].head())

  Price  Installs
0     0     10000
1     0    500000
2     0   5000000
3     0  50000000
4     0    100000

In [62]:
print(task3_df['Price'].iloc[0], type(task3_df['Price'].iloc[0]))
print(task3_df['Installs'].iloc[0], type(task3_df['Installs'].iloc[0]))

0 <class 'str'>
10000 <class 'numpy.int64'>

In [63]:
task3_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                        str
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
dtype: object

In [64]:
task3_df['Price']=task3_df['Price'].astype(float)
task3_df['Installs']=task3_df['Installs'].astype(int)

In [65]:
task3_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                    float64
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
dtype: object

In [66]:
task3_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [67]:
task3_df['Android Ver'].unique()[:15]

<StringArray>
[      '4.0.3 and up',         '4.2 and up',         '4.4 and up',
         '2.3 and up',         '3.0 and up',         '4.1 and up',
         '4.0 and up',       '2.3.3 and up', 'Varies with device',
         '2.2 and up',         '5.0 and up',         '6.0 and up',
         '1.6 and up',         '1.5 and up',         '2.1 and up']
Length: 15, dtype: str

In [68]:
(task3_df['Android Ver'] == 'Varies with device').sum()

np.int64(1178)

In [69]:
len(task3_df)

8892

In [70]:
task3_df['Revenue']=task3_df['Price']*task3_df['Installs']

In [71]:
filtered3_df=task3_df[
    (task3_df['Revenue'] >=10000) & 
    (task3_df['Installs'] >=10000) & 
    (task3_df['Content Rating'] == "Everyone")&
    (task3_df['App'].str.len() <= 30) & 
    (task3_df['Size'] >=15) 
]

In [72]:
filtered3_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month,Revenue
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39.0,100000,Paid,4.99,Everyone,Business,2017-04-11,3.4.6,3.0 and up,4,499000.0
853,Toca Life: City,EDUCATION,4.7,31085,24.0,500000,Paid,3.99,Everyone,Education;Pretend Play,2018-07-06,1.5-play,4.4 and up,7,1995000.0
854,Toca Life: Hospital,EDUCATION,4.7,3528,24.0,100000,Paid,3.99,Everyone,Education;Pretend Play,2018-06-12,1.1.1-play,4.4 and up,6,399000.0
1335,Meditation Studio,HEALTH_AND_FITNESS,4.6,1026,29.0,10000,Paid,3.99,Everyone,Health & Fitness,2018-05-15,1.0.6,4.3 and up,5,39900.0
1831,The Game of Life,GAME,4.4,18621,63.0,100000,Paid,2.99,Everyone,Board,2018-07-04,2.1.2,4.4 and up,7,299000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9678,Where's My Water?,FAMILY,4.7,188740,69.0,1000000,Paid,1.99,Everyone,Puzzle;Brain Games,2018-07-05,1.16.0,4.2 and up,7,1990000.0
9690,Out There Chronicles - Ep. 1,FAMILY,4.4,1516,44.0,50000,Paid,2.99,Everyone,Role Playing,2017-11-27,1.0.4,4.2 and up,11,149500.0
9728,Sonic 4™ Episode I,GAME,3.7,8014,37.0,100000,Paid,2.99,Everyone,Arcade,2016-04-04,1.5.0,2.2 and up,4,299000.0
9932,Campervan.Guide Pro,TRAVEL_AND_LOCAL,4.2,238,67.0,10000,Paid,5.99,Everyone,Travel & Local,2018-06-22,4.6.2,4.1 and up,6,59900.0
10682,Fruit Ninja Classic,GAME,4.3,85468,36.0,1000000,Paid,0.99,Everyone,Arcade,2018-06-08,2.4.1.485300,4.0.3 and up,6,990000.0

In [73]:
filtered3_df = filtered3_df[
    filtered3_df['Android Ver'] != 'Varies with device'
]

In [74]:
filtered3_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month,Revenue
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39.0,100000,Paid,4.99,Everyone,Business,2017-04-11,3.4.6,3.0 and up,4,499000.0
853,Toca Life: City,EDUCATION,4.7,31085,24.0,500000,Paid,3.99,Everyone,Education;Pretend Play,2018-07-06,1.5-play,4.4 and up,7,1995000.0
854,Toca Life: Hospital,EDUCATION,4.7,3528,24.0,100000,Paid,3.99,Everyone,Education;Pretend Play,2018-06-12,1.1.1-play,4.4 and up,6,399000.0
1335,Meditation Studio,HEALTH_AND_FITNESS,4.6,1026,29.0,10000,Paid,3.99,Everyone,Health & Fitness,2018-05-15,1.0.6,4.3 and up,5,39900.0
1831,The Game of Life,GAME,4.4,18621,63.0,100000,Paid,2.99,Everyone,Board,2018-07-04,2.1.2,4.4 and up,7,299000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9678,Where's My Water?,FAMILY,4.7,188740,69.0,1000000,Paid,1.99,Everyone,Puzzle;Brain Games,2018-07-05,1.16.0,4.2 and up,7,1990000.0
9690,Out There Chronicles - Ep. 1,FAMILY,4.4,1516,44.0,50000,Paid,2.99,Everyone,Role Playing,2017-11-27,1.0.4,4.2 and up,11,149500.0
9728,Sonic 4™ Episode I,GAME,3.7,8014,37.0,100000,Paid,2.99,Everyone,Arcade,2016-04-04,1.5.0,2.2 and up,4,299000.0
9932,Campervan.Guide Pro,TRAVEL_AND_LOCAL,4.2,238,67.0,10000,Paid,5.99,Everyone,Travel & Local,2018-06-22,4.6.2,4.1 and up,6,59900.0
10682,Fruit Ninja Classic,GAME,4.3,85468,36.0,1000000,Paid,0.99,Everyone,Arcade,2018-06-08,2.4.1.485300,4.0.3 and up,6,990000.0

In [75]:
filtered3_df['Android Ver']=filtered3_df['Android Ver'].str.replace('and','').str.replace('up','')

In [76]:
filtered3_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                    float64
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
Revenue                  float64
dtype: object

In [77]:
filtered3_df['Android Ver']=filtered3_df['Android Ver'].str.split('.')

In [78]:
filtered3_df['Android Ver'].head()

235     [3, 0  ]
853     [4, 4  ]
854     [4, 4  ]
1335    [4, 3  ]
1831    [4, 4  ]
Name: Android Ver, dtype: object

In [79]:
filtered3_df['Android Ver'] = filtered3_df['Android Ver'].str[:2]

In [80]:
filtered3_df['Android Ver'].head()

235     [3, 0  ]
853     [4, 4  ]
854     [4, 4  ]
1335    [4, 3  ]
1831    [4, 4  ]
Name: Android Ver, dtype: object

In [81]:
filtered3_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month,Revenue
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39.0,100000,Paid,4.99,Everyone,Business,2017-04-11,3.4.6,"[3, 0 ]",4,499000.0
853,Toca Life: City,EDUCATION,4.7,31085,24.0,500000,Paid,3.99,Everyone,Education;Pretend Play,2018-07-06,1.5-play,"[4, 4 ]",7,1995000.0
854,Toca Life: Hospital,EDUCATION,4.7,3528,24.0,100000,Paid,3.99,Everyone,Education;Pretend Play,2018-06-12,1.1.1-play,"[4, 4 ]",6,399000.0
1335,Meditation Studio,HEALTH_AND_FITNESS,4.6,1026,29.0,10000,Paid,3.99,Everyone,Health & Fitness,2018-05-15,1.0.6,"[4, 3 ]",5,39900.0
1831,The Game of Life,GAME,4.4,18621,63.0,100000,Paid,2.99,Everyone,Board,2018-07-04,2.1.2,"[4, 4 ]",7,299000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9678,Where's My Water?,FAMILY,4.7,188740,69.0,1000000,Paid,1.99,Everyone,Puzzle;Brain Games,2018-07-05,1.16.0,"[4, 2 ]",7,1990000.0
9690,Out There Chronicles - Ep. 1,FAMILY,4.4,1516,44.0,50000,Paid,2.99,Everyone,Role Playing,2017-11-27,1.0.4,"[4, 2 ]",11,149500.0
9728,Sonic 4™ Episode I,GAME,3.7,8014,37.0,100000,Paid,2.99,Everyone,Arcade,2016-04-04,1.5.0,"[2, 2 ]",4,299000.0
9932,Campervan.Guide Pro,TRAVEL_AND_LOCAL,4.2,238,67.0,10000,Paid,5.99,Everyone,Travel & Local,2018-06-22,4.6.2,"[4, 1 ]",6,59900.0
10682,Fruit Ninja Classic,GAME,4.3,85468,36.0,1000000,Paid,0.99,Everyone,Arcade,2018-06-08,2.4.1.485300,"[4, 0]",6,990000.0

In [82]:
filtered3_df['Android Ver'] = filtered3_df['Android Ver'].str.join('.')

In [83]:
filtered3_df['Android Ver'].head()

235     3.0
853     4.4
854     4.4
1335    4.3
1831    4.4
Name: Android Ver, dtype: object

In [84]:
filtered3_df['Android Ver'] = filtered3_df['Android Ver'].astype(float)

In [85]:
filtered3_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                    float64
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver              float64
Month                      int32
Revenue                  float64
dtype: object

In [86]:
top_3 = filtered3_df.groupby('Category')['Installs'].sum().nlargest(3)

In [87]:
top_3

Category
FAMILY             4940000
GAME               3100000
PERSONALIZATION    2060000
Name: Installs, dtype: int64

In [88]:
filtered3_df = filtered3_df[
    filtered3_df['Category'].isin(top_3.index)
]

In [89]:
filtered3_df['Category'].unique()

<StringArray>
['GAME', 'FAMILY', 'PERSONALIZATION']
Length: 3, dtype: str

In [90]:
task3_grouped = (
    filtered3_df
    .groupby(['Category', 'Type'])[['Installs', 'Revenue']]
    .mean()
)

In [91]:
task3_grouped

                           Installs        Revenue
Category        Type
FAMILY          Paid  170344.827586  509848.275862
GAME            Paid  163157.894737  324157.894737
PERSONALIZATION Paid  515000.000000  531100.000000

In [92]:
filtered3_df['Type'].value_counts()

Type
Paid    52
Name: count, dtype: int64

In [93]:
task3_grouped = task3_grouped.reset_index()

In [94]:
task3_grouped

          Category  Type       Installs        Revenue
0           FAMILY  Paid  170344.827586  509848.275862
1             GAME  Paid  163157.894737  324157.894737
2  PERSONALIZATION  Paid  515000.000000  531100.000000

In [95]:
fig3= make_subplots(specs=[[{"secondary_y": True}]])
fig3.add_trace(
    go.Bar(
        x=task3_grouped['Category'],
        y=task3_grouped['Installs'],
        name='Average Installs'
    ),
    secondary_y=False
)
fig3.add_trace(
    go.Scatter(
        x=task3_grouped['Category'],
        y=task3_grouped['Revenue'],
        mode='lines+markers',
        name='Average Revenue'
    ),
    secondary_y=True
)
fig3.update_layout(
    title='Average Installs vs Revenue for Top 3 Categories',
    xaxis_title='Category',
    template='simple_white',
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    margin=dict(l=10, r=10, t=30, b=10)
)

fig3.update_yaxes(title_text='Average Installs', secondary_y=False)
fig3.update_yaxes(title_text='Average Revenue ($)', secondary_y=True)

start_time = datetime.strptime("13:00", "%H:%M").time()
end_time = datetime.strptime("14:00", "%H:%M").time()

if start_time <= current_time <= end_time:
    fig3.show()
else:
    print("Chart is available only between 1:00 PM and 2:00 PM IST.")

Chart is available only between 1:00 PM and 2:00 PM IST.

In [96]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [97]:
task4_df=apps_df.copy()

In [98]:
task4_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [99]:
filtered4_df = task4_df[
    (task4_df['Reviews'] > 500) &
    (~task4_df['App'].str.startswith(('X', 'Y', 'Z'))) &
    (task4_df['Category'].str.startswith(('E', 'C', 'B'))) &
    (~task4_df['App'].str.contains('S', case=False, na=False))
]

In [100]:
filtered4_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
107,Ulta Beauty,BEAUTY,4.7,42050,NaN,1000000,Free,0,Everyone,Beauty,2018-06-05,5.4,5.0 and up,6
136,Rainbow Camera,BEAUTY,3.7,3871,23.0,1000000,Free,0,Everyone,Beauty,2018-07-30,2.2.0,4.0 and up,7
140,E-Book Read - Read Book for free,BOOKS_AND_REFERENCE,4.5,1857,4.9,50000,Free,0,Everyone,Books & Reference,2018-08-03,1.3.2,4.4 and up,8
141,Download free book with green book,BOOKS_AND_REFERENCE,4.6,4478,9.5,100000,Free,0,Everyone 10+,Books & Reference,2017-07-31,1.1,4.0 and up,7
142,Wikipedia,BOOKS_AND_REFERENCE,4.4,577550,NaN,10000000,Free,0,Everyone,Books & Reference,2018-08-02,Varies with device,Varies with device,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10289,Female Daily,BEAUTY,3.9,4354,42.0,100000,Free,0,Teen,Beauty,2018-08-06,2.5.1,4.0.3 and up,8
10445,Wi-Fi Auto-connect,COMMUNICATION,3.8,15036,NaN,1000000,Free,0,Everyone,Communication,2015-08-01,1.2.0,1.6 and up,8
10469,TownWiFi | Wi-Fi Everywhere,COMMUNICATION,3.9,2372,58.0,500000,Free,0,Everyone,Communication,2018-08-02,4.2.1,4.2 and up,8
10815,Golden Dictionary (FR-AR),BOOKS_AND_REFERENCE,4.2,5775,4.9,500000,Free,0,Everyone,Books & Reference,2018-07-19,7.0.4.6,4.2 and up,7
10829,Bulgarian French Dictionary Fr,BOOKS_AND_REFERENCE,4.6,603,7.4,10000,Free,0,Everyone,Books & Reference,2016-06-19,2.96,4.1 and up,6

In [101]:
len(filtered4_df)

214

In [102]:
filtered4_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
107,Ulta Beauty,BEAUTY,4.7,42050,NaN,1000000,Free,0,Everyone,Beauty,2018-06-05,5.4,5.0 and up,6
136,Rainbow Camera,BEAUTY,3.7,3871,23.0,1000000,Free,0,Everyone,Beauty,2018-07-30,2.2.0,4.0 and up,7
140,E-Book Read - Read Book for free,BOOKS_AND_REFERENCE,4.5,1857,4.9,50000,Free,0,Everyone,Books & Reference,2018-08-03,1.3.2,4.4 and up,8
141,Download free book with green book,BOOKS_AND_REFERENCE,4.6,4478,9.5,100000,Free,0,Everyone 10+,Books & Reference,2017-07-31,1.1,4.0 and up,7
142,Wikipedia,BOOKS_AND_REFERENCE,4.4,577550,NaN,10000000,Free,0,Everyone,Books & Reference,2018-08-02,Varies with device,Varies with device,8

In [103]:
filtered4_df['Category'] = filtered4_df['Category'].replace({
    'BEAUTY': 'सौंदर्य',
    'BUSINESS': 'வணிகம்',
    'DATING': 'Partnersuche'
})

In [104]:
filtered4_df['Category'].unique()

<StringArray>
[            'सौंदर्य', 'BOOKS_AND_REFERENCE',              'வணிகம்',
              'COMICS',       'COMMUNICATION',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS']
Length: 8, dtype: str

In [105]:
(filtered4_df['Category'] == 'Partnersuche').sum()

np.int64(0)

In [106]:
task4_grouped = (
    filtered4_df
    .groupby(['Month', 'Category'])['Installs']
    .sum()
    .reset_index()
)

In [107]:
task4_grouped

    Month             Category    Installs
0       1        COMMUNICATION    36100000
1       1            EDUCATION      100000
2       1        ENTERTAINMENT    20000000
3       2  BOOKS_AND_REFERENCE      100000
4       2               வணிகம்     1010000
5       3               COMICS      100000
6       3        COMMUNICATION    11200000
7       3        ENTERTAINMENT    20000000
8       3              सौंदर्य        5000
9       3               வணிகம்     1000000
10      4  BOOKS_AND_REFERENCE     2050000
11      4        COMMUNICATION     1100000
12      4        ENTERTAINMENT    10000000
13      5  BOOKS_AND_REFERENCE    40700000
14      5               COMICS      200000
15      5        COMMUNICATION     5000000
16      5            EDUCATION     2100000
17      5        ENTERTAINMENT     6000000
18      5               EVENTS       10000
19      5               வணிகம்      200000
20      6  BOOKS_AND_REFERENCE    47160000
21      6        COMMUNICATION    12100000
22      6            EDUCATION     1000000
23      6        ENTERTAINMENT    21100000
24      6               EVENTS      500000
25      6              सौंदर्य     1000000
26      6               வணிகம்    15200000
27      7  BOOKS_AND_REFERENCE   211700000
28      7               COMICS     6000000
29      7        COMMUNICATION   736840000
30      7            EDUCATION    29510000
31      7        ENTERTAINMENT   580800000
32      7               EVENTS     1100000
33      7              सौंदर्य     1000000
34      7               வணிகம்    11600000
35      8  BOOKS_AND_REFERENCE   120160000
36      8               COMICS     5050000
37      8        COMMUNICATION  2415510000
38      8            EDUCATION     4000000
39      8        ENTERTAINMENT    67200000
40      8              सौंदर्य      100000
41      8               வணிகம்   115100000
42      9        COMMUNICATION     1050000
43      9            EDUCATION     1000000
44      9        ENTERTAINMENT    11000000
45      9               வணிகம்     1100000
46     10  BOOKS_AND_REFERENCE      500000
47     10            EDUCATION     1000000
48     11  BOOKS_AND_REFERENCE     7000000
49     11        COMMUNICATION    16000000
50     11               வணிகம்      500000
51     12            EDUCATION     3100000
52     12               வணிகம்     1001000

In [108]:
task4_grouped['MoM_Growth'] = (
    task4_grouped
    .groupby('Category')['Installs']
    .pct_change()
)

In [109]:
task4_grouped.head(15)

    Month             Category  Installs  MoM_Growth
0       1        COMMUNICATION  36100000         NaN
1       1            EDUCATION    100000         NaN
2       1        ENTERTAINMENT  20000000         NaN
3       2  BOOKS_AND_REFERENCE    100000         NaN
4       2               வணிகம்   1010000         NaN
5       3               COMICS    100000         NaN
6       3        COMMUNICATION  11200000   -0.689751
7       3        ENTERTAINMENT  20000000    0.000000
8       3              सौंदर्य      5000         NaN
9       3               வணிகம்   1000000   -0.009901
10      4  BOOKS_AND_REFERENCE   2050000   19.500000
11      4        COMMUNICATION   1100000   -0.901786
12      4        ENTERTAINMENT  10000000   -0.500000
13      5  BOOKS_AND_REFERENCE  40700000   18.853659
14      5               COMICS    200000    1.000000

In [110]:
fig4= px.line(
    task4_grouped,
    x='Month',
    y='Installs',
    color='Category',
    markers=True,
    title='Monthly Install Trends by Category'
)
highlight_df = task4_grouped[
    task4_grouped['MoM_Growth'] > 0.20
]
fig4.add_scatter(
    x=highlight_df['Month'],
    y=highlight_df['Installs'],
    mode='markers',
    marker=dict(
        color='red',
        size=12,
        symbol='circle'
    ),
    name='Growth >20%'
)
fig4.update_layout(
    template='plotly_white',
    xaxis_title='Month',
    yaxis_title='Total Installs',
    legend_title='Category',
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    margin=dict(l=10, r=10, t=30, b=10)
)
start_time = datetime.strptime("18:00", "%H:%M").time()
end_time = datetime.strptime("21:00", "%H:%M").time()

if start_time <= current_time <= end_time:
    fig4.show()
else:
    print("Chart is available only between 6:00 PM and 9:00 PM IST.")

Chart is available only between 6:00 PM and 9:00 PM IST.

In [111]:
task5_df=merged_df.copy()

In [112]:
task5_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN,NaN,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122657,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0.0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122658,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0.0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122659,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0.0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122660,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0.0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN
122661,FP Notebook,MEDICAL,4.5,410,60M,50000,Free,0.0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up,NaN,NaN,NaN,NaN

In [113]:
task5_df.dtypes

App                           str
Category                      str
Rating                    float64
Reviews                       str
Size                          str
Installs                    int64
Type                          str
Price                     float64
Content Rating                str
Genres                        str
Last Updated                  str
Current Ver                   str
Android Ver                   str
Translated_Review             str
Sentiment                     str
Sentiment_Polarity        float64
Sentiment_Subjectivity    float64
dtype: object

In [114]:
task5_df['Reviews']=task5_df['Reviews'].astype(float)

In [115]:
filtered5_df = task5_df[
    (task5_df['Rating'] > 3.5) &
    (task5_df['Reviews'] > 500) &
    (task5_df['Installs'] > 50000 ) &
    (task5_df['Sentiment_Subjectivity'] > 0.5) &
    (~task5_df['App'].str.contains('S', case=False, na=False))&
    (task5_df['Category'].isin([
                               'GAME',
                               'BEAUTY',
                               'BUSINESS',
                               'COMICS',
                               'COMMUNICATION',
                               'DATING',
                               'ENTERTAINMENT',
                               'SOCIAL',
                               'EVENTS']))
        
]

In [116]:
filtered5_df['Category'] = filtered5_df['Category'].replace({
    'BEAUTY': 'सौंदर्य',
    'BUSINESS': 'வணிகம்',
    'DATING': 'Partnersuche'
})

In [117]:
filtered5_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
3068,Google Primer,வணிகம்,4.4,62272.0,18M,10000000,Free,0.0,Everyone,Business,"June 26, 2018",3.550.2,4.1 and up,Great,Positive,0.800000,0.750000
3070,Google Primer,வணிகம்,4.4,62272.0,18M,10000000,Free,0.0,Everyone,Business,"June 26, 2018",3.550.2,4.1 and up,Good,Positive,0.700000,0.600000
3115,Box,வணிகம்,4.2,159872.0,Varies with device,10000000,Free,0.0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device,I absolutely love app! It provides fast access...,Positive,0.544940,0.758333
3118,Box,வணிகம்,4.2,159872.0,Varies with device,10000000,Free,0.0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device,A impressive replacement Sharepoint useful peo...,Positive,0.577778,0.611111
3122,Box,வணிகம்,4.2,159872.0,Varies with device,10000000,Free,0.0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device,This incredibly helpful communicating tasks ne...,Positive,0.533333,0.616667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122454,Garena Free Fire,GAME,4.5,5534114.0,53M,100000000,Free,0.0,Teen,Action,"August 3, 2018",1.21.0,4.0.3 and up,I scratch redemption code purchasing Asus phon...,Positive,0.283333,0.716667
122455,Garena Free Fire,GAME,4.5,5534114.0,53M,100000000,Free,0.0,Teen,Action,"August 3, 2018",1.21.0,4.0.3 and up,Superb game...can u add guns like bazooka rock...,Positive,1.000000,1.000000
122456,Garena Free Fire,GAME,4.5,5534114.0,53M,100000000,Free,0.0,Teen,Action,"August 3, 2018",1.21.0,4.0.3 and up,"More guns must added+more stages,maps scopes g...",Positive,0.900000,0.625000
122459,Garena Free Fire,GAME,4.5,5534114.0,53M,100000000,Free,0.0,Teen,Action,"August 3, 2018",1.21.0,4.0.3 and up,The enemies die take like 30 bullets kill enem...,Neutral,0.000000,0.666667
122460,Garena Free Fire,GAME,4.5,5534114.0,53M,100000000,Free,0.0,Teen,Action,"August 3, 2018",1.21.0,4.0.3 and up,Very bad server... Please help it... I can't p...,Negative,-0.910000,0.866667

In [118]:
print(len(task5_df))

122662

In [119]:
f1 = task5_df[task5_df['Rating'] > 3.5]
print(len(f1))

120310

In [120]:
f2 = f1[f1['Reviews'] > 500]
print(len(f2))

117969

In [121]:
f3 = f2[f2['Installs'] > 50000]
print(len(f3))

116349

In [122]:
f4 = f3[f3['Sentiment_Subjectivity'] > 0.5]
print(len(f4))

35325

In [123]:
f5 = f4[~f4['App'].str.contains('S', case=False, na=False)]
print(len(f5))

11469

In [124]:
fig5=px.scatter(
    filtered5_df,
    x='Size',
    y='Rating',
    size='Installs',
    color='Category',
    hover_name ='App',
    color_discrete_map={'GAME': 'deeppink'},
)
fig5.update_layout(
    template='simple_white',
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis_title='App Size (MB)',
    yaxis_title='Average Rating',
    legend_title='Category',
    title='Relationship between App Size and Rating',
    margin=dict(l=10, r=10, t=30, b=10)
)
start_time = datetime.strptime("17:00", "%H:%M").time()
end_time = datetime.strptime("19:00", "%H:%M").time()

if start_time <= current_time <= end_time:
    fig5.show()
else:
    print("Chart is available only between 5:00 PM and 7:00 PM IST.")

Chart is available only between 5:00 PM and 7:00 PM IST.

In [125]:
task6_df=apps_df.copy()

In [126]:
task6_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [127]:
task6_df.dtypes

App                          str
Category                     str
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                         str
Price                        str
Content Rating               str
Genres                       str
Last Updated      datetime64[us]
Current Ver                  str
Android Ver                  str
Month                      int32
dtype: object

In [128]:
filtered6_df = task6_df[
    (task6_df['Rating'] >= 4.2) &
    (task6_df['Reviews'] > 1000) &
    (task6_df['Size'] >= 20) &
    (task6_df['Size'] <= 80) &
    (~task6_df['App'].str.contains('[0-9]', na=False))&
    (task6_df['Category'].str.startswith(('T','P'))) 
    ]

In [129]:
task6_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [130]:
summary6_df = (
    filtered6_df
    .groupby(['Month', 'Category'])['Installs']
    .sum()
    .reset_index()
)

In [131]:
summary6_df['Growth'] = summary6_df.groupby('Category')['Installs'].pct_change()

In [132]:
summary6_df['Growth'] > 0.25

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9     False
10     True
11    False
12     True
13     True
14     True
15    False
16    False
17     True
18     True
19     True
20     True
21     True
22    False
23     True
24    False
25     True
26    False
27    False
28    False
29    False
30    False
31     True
32     True
Name: Growth, dtype: bool

In [133]:
summary6_df.head()

   Month         Category  Installs  Growth
0      1  PERSONALIZATION  10000000     NaN
1      1      PHOTOGRAPHY  10000000     NaN
2      1            TOOLS   1000000     NaN
3      2  PERSONALIZATION  10000000     0.0
4      2     PRODUCTIVITY    100000     NaN

In [134]:
summary6_df['Highlight'] = summary6_df['Growth'] > 0.25

In [135]:
summary6_df['Category'].unique()

<StringArray>
[ 'PERSONALIZATION',      'PHOTOGRAPHY',            'TOOLS',
     'PRODUCTIVITY',        'PARENTING', 'TRAVEL_AND_LOCAL']
Length: 6, dtype: str

In [136]:
summary6_df['Category'] = summary6_df['Category'].replace({
    'TRAVEL_AND_LOCAL': 'Voyages et Local',
    'PRODUCTIVITY': 'Productividad',
    'PHOTOGRAPHY': '写真'
})

In [137]:
fig6 = px.area(
    summary6_df,
    x='Month',
    y='Installs',
    color='Category',
    title='Cumulative Installs Over Time by Category'
)
fig6.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis_title='Month',
    yaxis_title='Cumulative Installs',
    legend_title='Category',
    margin=dict(l=10, r=10, t=30, b=10)
)
start_time = datetime.strptime("16:00", "%H:%M").time()
end_time = datetime.strptime("18:00", "%H:%M").time()

if start_time <= current_time <= end_time:
    fig6.show()
else:
    print("Chart is available only between 4:00 PM and 6:00 PM IST.")

Chart is available only between 4:00 PM and 6:00 PM IST.

In [138]:
task2_df = apps_df.copy()

In [139]:
task2_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Month
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,1
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,6
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,6
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0,Everyone,Education,2017-07-25,1.48,4.1 and up,7
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2018-07-06,1.0,4.1 and up,7
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,1
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,7

In [140]:
filtered2_df = task2_df[
    (task2_df['Installs'] > 1000000) &
    (~task2_df['Category'].str.startswith(('S', 'A', 'C', 'G')))
]

In [141]:
filtered2_df.shape

(1555, 14)

In [142]:
summary2_df = (
    filtered2_df
    .groupby('Category')['Installs']
    .sum()
    .reset_index()
    .nlargest(5, 'Installs')
)

In [143]:
summary2_df

            Category     Installs
20      PRODUCTIVITY  12395000000
21             TOOLS  11325000000
7             FAMILY   9685000000
19       PHOTOGRAPHY   9660000000
22  TRAVEL_AND_LOCAL   6315000000

In [144]:
fig2= px.choropleth(
    summary2_df,
    locations='Category',
    color='Installs',
    title='Top 5 Categories by Installs'
)
fig2.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis_title='Month',
    yaxis_title='Cumulative Installs',
    legend_title='Category',
    margin=dict(l=10, r=10, t=30, b=10)
)
start_time = datetime.strptime("18:00", "%H:%M").time()
end_time = datetime.strptime("20:00", "%H:%M").time()

if start_time <= current_time <= end_time:
    fig2.show()
else:
    print("Chart is available only between 6:00 PM and 8:00 PM IST.")

Chart is available only between 6:00 PM and 8:00 PM IST.

In [145]:
insight1="The FAMILY category received the highest user engagement in terms of reviews, while average ratings remained relatively consistent across the top installed categories."
insight2="The visualization does not display highlighted regions because the dataset lacks geographic attributes required for choropleth mapping. Therefore, install statistics cannot be represented geographically."
insight3="PERSONALIZATION outperformed the other categories in both average installs and revenue, while FAMILY generated higher revenue than GAME despite comparable installation levels."
insight4= "COMMUNICATION dominated monthly installs with a sharp peak in Month 8, while growth markers highlight periods where category-wise installations increased by more than 20%."
insight5="Applications of different sizes generally achieve similar ratings, while the largest install counts are associated with apps maintaining consistently positive user ratings."
insight6= "The cumulative installation trend peaked during Months 7 and 8, primarily driven by Productivity, while Photography and Tools also contributed significantly to overall installations."

In [146]:
plot_width = 600
plot_height = 500

dashboard_html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Play Store Review Analytics</title>

    <style>

        body {{
            font-family: Arial, sans-serif;
            background-color: #333;
            color: white;
            margin: 0;
            padding: 0;
        }}

        .header {{
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #444;
            padding: 20px;
        }}

        .header img {{
            height: 50px;
            margin: 0 10px;
        }}

        .container {{
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            justify-items: center;
            padding: 20px;
        }}

        .plot-container {{
            border: 2px solid #555;
            background-color: #222;
            padding: 10px;
            width: {plot_width}px;
            height: {plot_height}px;
            position: relative;
            overflow: hidden;
            cursor: pointer;
        }}

        .plot-container iframe {{
            width: 100%;
            height: 100%;
            border: none;
        }}

        .insights {{
            display: none;
            position: absolute;
            top: 10px;
            right: 10px;
            background: rgba(0,0,0,0.8);
            color: white;
            padding: 8px;
            border-radius: 5px;
            font-size: 12px;
            max-width: 220px;
            z-index: 10;
        }}

        .plot-container:hover .insights {{
            display: block;
        }}

    </style>

</head>

<body>

<div class="header">
    <img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" alt="Google Logo">

    <h1>Google Play Store Reviews Analytics</h1>

    <img src="https://upload.wikimedia.org/wikipedia/commons/7/78/Google_Play_Store_badge_EN.svg" alt="Play Store">
</div>

<div class="container">

{plots}

</div>

</body>
</html>
"""

In [147]:
from datetime import datetime
import os
import plotly.io as pio

def save_plot_as_html(fig, filename, insight, start_hour, end_hour):
    global plot_containers

    filepath = os.path.join(html_files_path, filename)

    # Always save the individual HTML file
    fig.write_html(
        filepath,
        full_html=False,
        include_plotlyjs="inline"
    )

    # Current IST hour
    current_hour = datetime.now().hour

    # Only add to dashboard during allowed time
    if start_hour <= current_hour < end_hour:

        html_content = pio.to_html(
            fig,
            full_html=False,
            include_plotlyjs="inline"
        )

        plot_containers += f"""
        <div class="plot-container" id="{filename}" onclick="openPlot('{filename}')">
            <div class="plot">
                {html_content}
            </div>
            <div class="insights">
                {insight}
            </div>
        </div>
        """
    else:
       plot_containers += f"""
       <div class="plot-container">
            <div style="
                display:flex;
                justify-content:center;
                align-items:center;
                height:100%;
                text-align:center;
                font-size:20px;
                font-weight:bold;
                color:white;
                padding:20px;">
                Chart is available only between
                {start_hour}:00 and {end_hour}:00 IST.
            </div>
        </div>
 
        """

    print(filename)

In [148]:
save_plot_as_html(fig1, "Category chart 1.html", insight1, 15, 17)
save_plot_as_html(fig2, "Choropleth Map 2.html", insight2, 18, 20)
save_plot_as_html(fig3, "Free vs Paid chart 3.html", insight3, 13, 14)
save_plot_as_html(fig4, "Trend of Installs over time 4.html", insight4, 18, 21)
save_plot_as_html(fig5, "Relationship between App Size and Rating Chart 5.html", insight5, 17, 19)
save_plot_as_html(fig6, "Stacked Area Chart 6.html", insight6, 16, 18)

Category chart 1.html
Choropleth Map 2.html
Free vs Paid chart 3.html
Trend of Installs over time 4.html
Relationship between App Size and Rating Chart 5.html
Stacked Area Chart 6.html

In [149]:
final_html = dashboard_html.format(
    plots=plot_containers,
    plot_width=plot_width,
    plot_height=plot_height
)

In [150]:
dashboard_path = "./web page.html"

with open(dashboard_path, "w", encoding="utf-8") as f:
    f.write(final_html)

import subprocess
import os

chrome_path = r"C:\Program Files\Google\Chrome\Application\chrome.exe"

subprocess.Popen([
    chrome_path,
    os.path.abspath(dashboard_path)
])